### ISSUE TITLE
Unable to catch bad requests

### ISSUE THREAD

**Issue by aivong3** [fastly/expressly#51]
**Version**

2.0.1

**What happened**

We would like to be able to catch and log exceptions such as bad requests. It looks like the bad request 400 status code is returned by the [runtime](https://github.com/fastly/js-compute-runtime/blob/main/runtime/js-compute-runtime/builtins/request-response.cpp#L2107). Can expressly throw an error that we can catch for these requests? We are using custom error middleware and they are not catching 400s.

A bad request to an expressly service can be recreated with:

```
curl -svo /dev/null  "http://127.0.0.1:PORT/<"
```

**Comment by doramatadora** [comment]
Hi @aivong3,

This looks like a runtime issue, rather than an expressly issue. 

Taking the following Compute application, which should return OK (HTTP 200) *on any route*, and running `curl -svo /dev/null  "http://127.0.0.1:7676/<"`, produces the same `400 Bad Request` response:

```js
/// <reference types="@fastly/js-compute" />

addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));

async function handleRequest(event) {
  console.log(`Request received in Compute: ${event.request.method} ${event.request.url}`)
  return new Response("OK", { status: 200 });
}
```
 
I am therefore redirecting this issue to the runtime team – CC @JakeChampion 

I suspect it's something to do with the `<` in particular.

Running the following:
```sh
curl -svo /dev/null  "http://127.0.0.1:7676/not-a-route"
curl -svo /dev/null  "http://quickly-sure-caribou.edgecompute.app/not-a-route"
``` 

In expressly:
```js 
import { Router } from "@fastly/expressly";

const router = new Router();

router.use((req, res) => {
  console.log(`Request received: ${req.method} ${req.url}`);
});

router.get("/", async (req, res) => {
  return res.send("Hello world!");
});

router.use((err, req, res) => {
  console.error(err);
  res.withStatus(500).send(`Uh-oh! Something went wrong: ${err.message}`);
});

router.listen();```

Results in the appropriate logs and 500 error, as expected.

**Comment by aivong3** [comment]
Hi @doramatadora,

Thanks for taking a look! It would be nice to have the flexibility to handle these bad requests in a custom way like we can for the other errors. Will see if this is possible with the runtime team

**Comment by doramatadora** [comment]
Hi @aivong3, I'll close this issue now, with some additional context:

- the behaviour is limited to non-[RFC3986](https://tools.ietf.org/html/rfc3986#section-3.3) compliant paths
- the underlying issue stems from the `httparse` library upstream (via `hyper`, in our Compute host): https://github.com/seanmonstar/httparse/issues/146
- because of the potential security implications, we'd first need to carefully define what additional syntax we'd like to accept; preferably there would be a basis in a spec, at the very least a modification to the ABNF of a spec that limits the scope of the change.
